### ISSUE TITLE
Add option on settings page for deleting a Good Card account.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#66] opened 2022-11-02 16:21 UTC
There should be some button that a user can click to delete their account with Goon Card (not a single social media account, but the actual Goon Card account that we have stored in the database). This button should have some kind of confirmation message or alert asking if they really want to delete their account, then call the backend API for account deletion.

**Comment by sderacy** [comment] 2022-11-02 17:53
We could put this on the profile page where you add social media accounts. If we do, we would just need to have headers or some divider and then we can put the button on the page in a way that makes sense.

We should change the name of the social media accounts link to Profile to encompass this

**Comment by thadakn1** [comment] 2022-11-05 19:50
Maybe we should put the option to delete the account on the settings page instead of social media accounts page. but i agree with sterly, we should rename that social media links page to "Profile" and i went ahead and did it, I just want to hear everyone's opinion on whether they think we should have the delete option in the settings page instead. usually that's where it is for other apps or services

**Comment by paytonshaltis** [comment] 2022-11-05 20:30
> Maybe we should put the option to delete the account on the settings page instead of social media accounts page. but i agree with sterly, we should rename that social media links page to "Profile" and i went ahead and did it, I just want to hear everyone's opinion on whether they think we should have the delete option in the settings page instead. usually that's where it is for other apps or services

Thinking about this now, I think moving the 'delete account' button to the settings page may be the way to go Nisha. The profile page should really just focus on adding, editing, and deleting the user's social media accounts, and an additional 'delete' button on this page may confuse the user into thinking that they are just deleting one of their linked social media accounts and not their entire account.

**Comment by sderacy** [comment] 2022-11-05 20:45
Nisha raises a fair point. Similar to the original plan, the page will need a little restructuring so that the "delete account button" doesn't stand out awkwardly compared to the other elements. Also, I took Leah and myself off of this issue since I thought Nisha was doing this one but I don't think she actually confirmed whether she was. @thadakn1 do you want to take this issue? If not I can probably add it after I add the settings functionality

**Comment by thadakn1** [comment] 2022-11-06 05:30
yep! i'll take this issue, sorry i didn't get a chance to self-assign it earlier

**Comment by thadakn1** [comment] 2022-11-06 05:31
@paytonshaltis you just need me to get the button on the profile page right? so, will you work on the deletion on the backend side?

**Comment by paytonshaltis** [comment] 2022-11-06 16:27
> @paytonshaltis you just need me to get the button on the profile page right? so, will you work on the deletion on the backend side?

Yup! Just have a button that maybe does the same confirmation alert that Leah has for deleting an individual linked account ("are you sure you want to delete?" type of message), and I will connect it to the backend.

**Closed** 2022-11-15 14:35 UTC
Labels: frontend
